console.log("putanignamo");
console.log("putanginamo adrian");
console.log("putangina ninyong lahat");
console.log("Trying out the GIT REVERT");
console.log("AT KAHIT MAHAL KITA");
console.log("pangarap lang kita");
console.log("hsfidhfsd");
console.log("this is a feature");
console.log("ohmahgah bro");
console.log("isapa");
console.log("eto pa");
